### ISSUE TITLE
Blazing Blood imposible to make

### ISSUE THREAD

**Issue by tempodat** [ianm1647/NaturesMinerals#2]
I can't make Blazing Blood as the fluid required, tconstruct:molten_blaze, does not exist, might have been moved or renamed.

**Comment by tempodat** [comment]
![image](https://user-images.githubusercontent.com/46243210/123641074-85cd9180-d82a-11eb-8ac2-b48280f76f69.png)

**Comment by ianm1647** [comment]
im working on a fix rn, it should be out soon
